<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" errorPage="error.jsp"%>
<%@ page import="java.sql.*" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	
	<%
		//On this page, PostGres database connection is being established, data is being retrieved
		//and that data is being displayed on the page
		
		/*
		It is not recommended to perform any kind of business logic with Java written on a JSP page
		
		In this scenario, best practice would be to write all business logic into a Model View Controller (MVC)
		which serves as the servlet where the business logic lives. The JSP page in turn serves as only a view 
		which is populated by a model object. This model object is a simple POJO generated by the controller servlet
		and used to carry the data that will be used on the page that the user views. 
		
		N-Tier architecture: breaking up the architecture of programs to have a clear seperation of duty.
		It would be even better for the servlet only to control things that are to be sent to the page. Therefore
		a seperate class that does some logical work could be used by the servlet which itself uses another class
		called a DAO (data access object) that retrieves data from the db
		*/
		Class.forName("org.postgresql.Driver");
	
		String url = "jdbc:postgresql://localhost:5432/students";
		String userName = "postgres";
		String password = "pass123";
		
		String sql = "SELECT * FROM students WHERE NAME='Travis';";
		
		Connection con = DriverManager.getConnection(url, userName, password);
		System.out.println("DB connection is established");
		
		Statement st = con.createStatement();
		
		ResultSet rs = st.executeQuery(sql);
		rs.next();
	%>
	
	Roll Number: <%= rs.getString(1) %><br>
	Marks: <%= rs.getString(2) %><br>
	Name: <%= rs.getString(3) %>
		
	<%
		con.close();
		System.out.println("DB connection is closed");
	%>
	
</body>
</html>